### ISSUE TITLE
Exception thrown checking for sell mode on lowbb buy

### ISSUE THREAD

**Issue by mehtadone** [taniman/proxy-bot#105]
I just ran up proxybot and got the following on the console. It is still running but I thought it might be useful info: 

        2017-10-06 07:24:16 ERROR BBStrategyRunner - An error occured
java.lang.NullPointerException: null
        at nl.komtek.gpi.bot.strategy.helper.StrategyRunnerHelper.sellOnlyModeEnabled(StrategyRunnerHelper.java:97) ~[classes!/:1.2.0]
        at nl.komtek.gpi.services.ProxyBotService.buyOrder(ProxyBotService.java:551) ~[classes!/:1.2.0]
        at nl.komtek.gpi.services.ProxyBotService$$FastClassBySpringCGLIB$$82cc1c87.invoke(<generated>) ~[classes!/:1.2.0]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:345) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:408) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61) ~[spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656) ~[spring-aop-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at nl.komtek.gpi.services.ProxyBotService$$EnhancerBySpringCGLIB$$7abb4ad1.buyOrder(<generated>) ~[classes!/:1.2.0]
        at nl.komtek.gpi.strategyrunner.BBStrategyRunner.buy(BBStrategyRunner.java:249) ~[classes!/:1.2.0]
        at nl.komtek.gpi.strategyrunner.BBStrategyRunner.checkBBBuyStrategy(BBStrategyRunner.java:96) [classes!/:1.2.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

AND 

2017-10-06 07:27:00 ERROR BBStrategyRunner - An error occured
java.lang.NullPointerException: null
        at nl.komtek.gpi.bot.strategy.helper.StrategyRunnerHelper.sellOnlyModeEnabled(StrategyRunnerHelper.java:97) ~[classes!/:1.2.0]
        at nl.komtek.gpi.services.ProxyBotService.buyOrder(ProxyBotService.java:551) ~[classes!/:1.2.0]
        at nl.komtek.gpi.services.ProxyBotService$$FastClassBySpringCGLIB$$82cc1c87.invoke(<generated>) ~[classes!/:1.2.0]
        at org.springframework.cglib.proxy.MethodProxy.invoke(

**Comment by mehtadone** [comment]
[
[ProxyBot.log](https://github.com/taniman/proxy-bot/files/1361887/ProxyBot.log)
](url)
