### ISSUE TITLE
Java Error

### ISSUE THREAD

**Issue by vr0** [taniman/proxy-bot#97]
Hello,

System: Ubuntu 16.04.3 LTS
Java: openjdk-8-jre-headless
```
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```
After some time i got this error message:

```
0|proxybot | 2017-09-30 19:20 +02:00: 2017-09-30 19:20:17 ERROR BBStrategyRunner - An error occured
0|proxybot | com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
0|proxybot |    at com.google.gson.Gson.fromJson(Gson.java:891) ~[gson-2.6.2.jar!/:?]
0|proxybot |    at com.google.gson.Gson.fromJson(Gson.java:844) ~[gson-2.6.2.jar!/:?]
0|proxybot |    at com.google.gson.Gson.fromJson(Gson.java:793) ~[gson-2.6.2.jar!/:?]
0|proxybot |    at com.google.gson.Gson.fromJson(Gson.java:765) ~[gson-2.6.2.jar!/:?]
0|proxybot |    at com.cf.data.map.poloniex.PoloniexDataMapper.mapChartData(PoloniexDataMapper.java:49) ~[PoloniexClient-1.1.5.jar!/:?]
0|proxybot |    at nl.komtek.gpi.bot.strategy.helper.TimeSeriesHelper.createTimeSeries(TimeSeriesHelper.java:22) ~[classes!/:1.0.9.1]
0|proxybot |    at nl.komtek.gpi.bot.strategy.helper.BBHelper.createBBLow(BBHelper.java:24) ~[classes!/:1.0.9.1]
0|proxybot |    at nl.komtek.gpi.strategyrunner.BBStrategyRunner.isLowBBBuyPositive(BBStrategyRunner.java:341) ~[classes!/:1.0.9.1]
0|proxybot |    at nl.komtek.gpi.strategyrunner.BBStrategyRunner.buy(BBStrategyRunner.java:195) ~[classes!/:1.0.9.1]
0|proxybot |    at nl.komtek.gpi.strategyrunner.BBStrategyRunner.checkBBBuyStrategy(BBStrategyRunner.java:97) [classes!/:1.0.9.1]
0|proxybot |    at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source) ~[?:?]
0|proxybot |    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
0|proxybot |    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
0|proxybot |    at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
0|proxybot |    at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
0|proxybot |    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
0|proxybot |    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_131]
0|proxybot |    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_131]
0|proxybot |    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_131]
0|proxybot |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_131]
0|proxybot |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_131]
0|proxybot |    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
0|proxybot | Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
0|proxybot |    at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:351) ~[gson-2.6.2.jar!/:?]
0|proxybot |    at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:70) ~[gson-2.6.2.jar!/:?]
0|proxybot |    at com.google.gson.Gson.fromJson(Gson.java:879) ~[gson-2.6.2.jar!/:?]
0|proxybot |    ... 21 more
0|proxybot | 2017-09-30 19:20 +02:00: 2017-09-30 19:20:23 ERROR BBStrategyRunner - An error occured
0|proxybot | com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
0|proxybot |    at com.google.gson.Gson.fromJson(Gson.java:891) ~[gson-2.6.2.jar!/:?]
0|proxybot |    at com.google.gson.Gson.fromJson(Gson.java:844) ~[gson-2.6.2.jar!/:?]
0|proxybot |    at com.google.gson.Gson.fromJson(Gson.java:793) ~[gson-2.6.2.jar!/:?]
0|proxybot |    at com.google.gson.Gson.fromJson(Gson.java:765) ~[gson-2.6.2.jar!/:?]
0|proxybot |    at com.cf.data.map.poloniex.PoloniexDataMapper.mapChartData(PoloniexDataMapper.java:49) ~[PoloniexClient-1.1.5.jar!/:?]
0|proxybot |    at nl.komtek.gpi.bot.strategy.helper.TimeSeriesHelper.createTimeSeries(TimeSeriesHelper.java:22) ~[classes!/:1.0.9.1]
0|proxybot |    at nl.komtek.gpi.bot.strategy.helper.BBHelper.createBBLow(BBHelper.java:24) ~[classes!/:1.0.9.1]
0|proxybot |    at nl.komtek.gpi.strategyrunner.BBStrategyRunner.isLowBBBuyPositive(BBStrategyRunner.java:341) ~[classes!/:1.0.9.1]
0|proxybot |    at nl.komtek.gpi.strategyrunner.BBStrategyRunner.buy(BBStrategyRunner.java:195) ~[classes!/:1.0.9.1]
0|proxybot |    at nl.komtek.gpi.strategyrunner.BBStrategyRunner.checkBBBuyStrategy(BBStrategyRunner.java:97) [classes!/:1.0.9.1]
0|proxybot |    at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source) ~[?:?]
0|proxybot |    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
0|proxybot |    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
0|proxybot |    at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
0|proxybot |    at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
0|proxybot |    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
0|proxybot |    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_131]
0|proxybot |    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_131]
0|proxybot |    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_131]
0|proxybot |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_131]
0|proxybot |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_131]
0|proxybot |    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
0|proxybot | Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
0|proxybot |    at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:351) ~[gson-2.6.2.jar!/:?]
0|proxybot |    at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:70) ~[gson-2.6.2.jar!/:?]
0|proxybot |    at com.google.gson.Gson.fromJson(Gson.java:879) ~[gson-2.6.2.jar!/:?]
0|proxybot |    ... 21 more
0|proxybot | 2017-09-30 19:20 +02:00: 2017-09-30 19:20:37 ERROR BBStrategyRunner - An error occured
0|proxybot | com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
0|proxybot |    at com.google.gson.Gson.fromJson(Gson.java:891) ~[gson-2.6.2.jar!/:?]
0|proxybot |    at com.google.gson.Gson.fromJson(Gson.java:844) ~[gson-2.6.2.jar!/:?]
0|proxybot |    at com.google.gson.Gson.fromJson(Gson.java:793) ~[gson-2.6.2.jar!/:?]
0|proxybot |    at com.google.gson.Gson.fromJson(Gson.java:765) ~[gson-2.6.2.jar!/:?]
0|proxybot |    at com.cf.data.map.poloniex.PoloniexDataMapper.mapChartData(PoloniexDataMapper.java:49) ~[PoloniexClient-1.1.5.jar!/:?]
0|proxybot |    at nl.komtek.gpi.bot.strategy.helper.TimeSeriesHelper.createTimeSeries(TimeSeriesHelper.java:22) ~[classes!/:1.0.9.1]
0|proxybot |    at nl.komtek.gpi.bot.strategy.helper.BBHelper.createBBLow(BBHelper.java:24) ~[classes!/:1.0.9.1]
0|proxybot |    at nl.komtek.gpi.strategyrunner.BBStrategyRunner.isLowBBBuyPositive(BBStrategyRunner.java:341) ~[classes!/:1.0.9.1]
0|proxybot |    at nl.komtek.gpi.strategyrunner.BBStrategyRunner.buy(BBStrategyRunner.java:195) ~[classes!/:1.0.9.1]
0|proxybot |    at nl.komtek.gpi.strategyrunner.BBStrategyRunner.checkBBBuyStrategy(BBStrategyRunner.java:97) [classes!/:1.0.9.1]
0|proxybot |    at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source) ~[?:?]
0|proxybot |    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
0|proxybot |    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
0|proxybot |    at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
0|proxybot |    at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
0|proxybot |    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
0|proxybot |    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_131]
0|proxybot |    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_131]
0|proxybot |    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_131]
0|proxybot |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_131]
0|proxybot |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_131]
0|proxybot |    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
0|proxybot | Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $
0|proxybot |    at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:351) ~[gson-2.6.2.jar!/:?]
0|proxybot |    at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:70) ~[gson-2.6.2.jar!/:?]
0|proxybot |    at com.google.gson.Gson.fromJson(Gson.java:879) ~[gson-2.6.2.jar!/:?]
0|proxybot |    ... 21 more
```
Kind Regards,
vr0

**Comment by taniman** [comment]
just polo acting up. so nothing to worry about. I am trying to make thouse errors nicer though
